#pragma once
#include <vector>
#include <string>
#include <sstream>
#include <iostream>
#include <map>
#include <cmath>
#include "geometry.h"

namespace jotcad {
namespace geo {

class OBJWriter {
    std::vector<std::string> lines;
public:
    void add_geometry(const Geometry& geo) {
        // Output vertices
        for (const auto& v : geo.vertices) {
            std::stringstream ss;
            ss << "v " << CGAL::to_double(v.x) << " " << CGAL::to_double(v.y) << " " << CGAL::to_double(v.z);
            lines.push_back(ss.str());
        }
        // Output triangles (1-based index)
        for (const auto& t : geo.triangles) {
            std::stringstream ss;
            ss << "f " << (t[0] + 1) << " " << (t[1] + 1) << " " << (t[2] + 1);
            lines.push_back(ss.str());
        }
        // Output complex faces
        for (const auto& f : geo.faces) {
            for (const auto& loop : f.loops) {
                if (loop.empty()) continue;
                std::stringstream ss;
                ss << "f";
                for (int idx : loop) {
                    ss << " " << (idx + 1);
                }
                lines.push_back(ss.str());
            }
        }
    }

    std::string write_text() const {
        std::stringstream ss;
        ss << "# Generated by JotCAD\n";
        for (const auto& line : lines) {
            ss << line << "\n";
        }
        return ss.str();
    }
};

class OBJReader {
public:
    static bool read_text(const std::string& text, Geometry& out_geo) {
        std::istringstream stream(text);
        std::string line;
        
        out_geo.vertices.clear();
        out_geo.triangles.clear();
        out_geo.faces.clear();
        
        while (std::getline(stream, line)) {
            // Trim leading/trailing whitespace
            size_t start = line.find_first_not_of(" \t\r\n");
            if (start == std::string::npos) continue;
            line = line.substr(start);
            
            if (line.rfind("v ", 0) == 0) {
                std::stringstream ss(line.substr(2));
                double x, y, z;
                if (ss >> x >> y >> z) {
                    Vertex v;
                    v.x = (FT)x;
                    v.y = (FT)y;
                    v.z = (FT)z;
                    out_geo.vertices.push_back(v);
                }
            } else if (line.rfind("f ", 0) == 0) {
                std::stringstream ss(line.substr(2));
                std::string part;
                std::vector<int> indices;
                while (ss >> part) {
                    size_t slash = part.find('/');
                    std::string idx_str = (slash == std::string::npos) ? part : part.substr(0, slash);
                    if (!idx_str.empty()) {
                        try {
                            int idx = std::stoi(idx_str);
                            if (idx > 0) {
                                indices.push_back(idx - 1);
                            } else if (idx < 0) {
                                indices.push_back((int)out_geo.vertices.size() + idx);
                            }
                        } catch (...) {}
                    }
                }
                if (indices.size() == 3) {
                    out_geo.triangles.push_back({indices[0], indices[1], indices[2]});
                } else if (indices.size() > 3) {
                    // Triangulate convex face as a fan
                    for (size_t i = 1; i < indices.size() - 1; ++i) {
                        out_geo.triangles.push_back({indices[0], (int)indices[i], (int)indices[i+1]});
                    }
                }
            }
        }
        return !out_geo.vertices.empty();
    }
};

} // namespace geo
} // namespace jotcad
