import { runIntegrationTest } from './harness.js';
import assert from 'node:assert';

process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

runIntegrationTest('G-code Slicing via PrusaSlicer Integration', async ({ vfs, mesh, compiler, parser, readData }) => {
    // --- Test Step 1: Create a box and slice to G-code ---
    const sliceCode = 'Box(10, 10, 10).gcode("test_box.gcode", layer_height: 0.2, center: "100,100").file -> file';
    console.log(`[Test] Evaluating G-code slicing DSL: ${sliceCode}`);

    const ast = parser.parse(sliceCode);
    const terminals = await compiler.evaluate(ast, {}, {
        outputs: { "file": { type: "file" } }
    });

    const terminalBundle = terminals.find(t => t.selector.output === 'file');
    assert.ok(terminalBundle, "Should find terminal output bundle for file");

    console.log("[Test] Fetching G-code output from VFS...");
    const gcodeData = await readData(terminalBundle.selector);
    const gcodeText = (typeof gcodeData === 'string')
        ? gcodeData
        : new TextDecoder().decode(gcodeData);

    assert.ok(gcodeText.length > 0, "G-code output must not be empty");
    assert.ok(gcodeText.includes("G1") || gcodeText.includes("M107") || gcodeText.includes("generated by PrusaSlicer"), 
              "G-code output should contain standard G-code commands or PrusaSlicer header");
    console.log("✔ G-code Slicing evaluated successfully. Output length:", gcodeText.length);
});
