# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main, fs-v2]
  pull_request:
    branches: [main, fs-v2]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install JS Deps
        run: npm ci
      - name: Install Chrome for Puppeteer
        run: |
          rm -rf ~/.cache/puppeteer
          node node_modules/puppeteer/lib/cjs/puppeteer/node/cli.js browsers install chrome
      - name: Setup & Build Native Ops
        run: |
          sudo apt-get update && sudo apt-get install -y xvfb libgbm1
          ./scripts/generate_dev_cert.sh
          npm run install_deps
          npm run setup
          npm run build:test --workspace=ux
      - name: Run CI Suite
        run: npm run ci
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          LOG_LEVEL: ERROR
